server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/predictiondb
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

ml:
  service:
    url: http://ml-service:5000/predict